### ISSUE TITLE
Regarding the dataset extraction

### ISSUE THREAD

**Issue by shreejalt** [DengpanFu/LUPerson#10]
Hi @DengpanFu  Thanks for your work. Can you please help me in figuring out the extraction of data from youtube videos as the dets.pkl don't contain the resolution images and every youtube video is different in res when extracted

**Comment by DengpanFu** [comment]
We have released the download and extract scripts, and also there's someone has rebuilt the dataset, please refer to https://github.com/DengpanFu/LUPerson/issues/8#issuecomment-1004611808
