### ISSUE TITLE
About keys.pkl

### ISSUE THREAD

**Issue by ShinYoung-hwan** [DengpanFu/LUPerson#11]
It seems very interesting work!
I have some questions about the work.

How can I get keys.pkl file?

**Comment by shreejalt** [comment]
It is in the vnames.txt file.
But the problem is of resolution. dets.pkl doesn't contain the resolution of videos

**Comment by ShinYoung-hwan** [comment]
Thank you. I solve keys.pkl problem.

However I get another problem.
lmdb.Error: Caught Error in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "/home/user/.local/lib/python3.7/site-packages/torch/utils/data/_utils/worker.py", line 287, in _worker_loop
    data = fetcher.fetch(index)
  File "/home/user/.local/lib/python3.7/site-packages/torch/utils/data/_utils/fetch.py", line 44, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/user/.local/lib/python3.7/site-packages/torch/utils/data/_utils/fetch.py", line 44, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/user/clone/LUPerson/lup_moco/libs/dataset.py", line 51, in __getitem__
    self._init_lmdb()
  File "/home/user/clone/LUPerson/lup_moco/libs/dataset.py", line 47, in _init_lmdb
    readahead=False, meminit=False)
lmdb.Error: /home/user/clone/LUPerson/LUP/lmdbs/lmdb: No such file or directory


In fact, I already have that directory. How can I solve it?

**Comment by shreejalt** [comment]
@ShinYoung-hwan , 
How did you extracted the crops from the dets.pkl file?
It seems that the videos are of different resolution 
if you have done it , can you send me the script?

**Comment by whobefore** [comment]
So have you both extracted the crops from the dets.pkl file? If yes, could you send me the script too? Thanks!

**Comment by oliver8459** [comment]
@shreejalt Hi~ Have you dealt with the solution problem? Thanks!

**Comment by shreejalt** [comment]
@oliver8459, 
No I didn't get the crops. I tried some heuristics which is kind of a stochastic process.  Sometimes it comes, sometimes it doesn't.

**Comment by DengpanFu** [comment]
We have released the download and extract scripts, and also there's someone has rebuilt the dataset, please refer to https://github.com/DengpanFu/LUPerson/issues/8#issuecomment-1004611808
