### ISSUE TITLE
How can i get LUP/lmdbs/lmdb

### ISSUE THREAD

**Issue by vanmeruso** [DengpanFu/LUPerson#12]
In run_moco.sh ,There is --data_path "${DIR}/LUP/lmdbs/lmdb"
however I can't found LUP/lmdbs/lmdb in my git clone.
How can i get LUP/lmdbs/lmdb?

**Comment by DengpanFu** [comment]
We have released the download and extract scripts, and also there's someone has rebuilt the dataset, please refer to https://github.com/DengpanFu/LUPerson/issues/8#issuecomment-1004611808
