### ISSUE TITLE
哈喽，有没有人分享一下LUPerson这份数据不是分文件压缩的数据集的下载链接

### ISSUE THREAD

**Issue by APeiZou** [DengpanFu/LUPerson#18]
哈喽，有没有人分享一下LUPerson这份数据不是分文件压缩的数据集的下载链接

**Comment by wqjv** [comment]
> 哈喽，有没有人分享一下LUPerson这份数据不是分文件压缩的数据集的下载链接

您好，请问是已经有了吗，可以分享一下吗
