### ISSUE TITLE
How to inference 

### ISSUE THREAD

**Issue by swingbalance** [DengpanFu/LUPerson#2]
Hi,

what a impressive concept from your paper

I found demo.py in fast-reid/demo/ for inference,
but I can't ensure arguments when running : python demo.py --config-file [arg1] --parallel -- opts MODEL.WEIGHTS [arg2]

could you give a example ?

**Comment by DengpanFu** [comment]
I have add an example for fast-reid inference. Please see fast-reid/README.md and have a try.
