### ISSUE TITLE
LUPerson Dataset dets.pkl resolution

### ISSUE THREAD

**Issue by ivskaikai** [DengpanFu/LUPerson#7]
How to know LUPerson Dataset dets.pkl resolution

**Comment by shreejalt** [comment]
@ivskaikai Did you figured the way of getting crops ? I am getting random crops and there are no persons

**Comment by DengpanFu** [comment]
youtube-dl is used to download raw videos, and the download configs can be found at: https://github.com/DengpanFu/LUPerson/blob/a5b7c69958cfe23e59bc3d1c62896053cb4356fa/LUP/download.py#L19
